#!/bin/bash
set -e

ARTIFACTS_DIR=$HOME/nano_789/nanochat_artifacts

# ---------------- hf_base ----------------
hf download crellis/d18-20tpp-hf-base            --local-dir "$ARTIFACTS_DIR/hf_base/d18_20tpp"
hf download crellis/d18-20tpp-drope-50-hf-base   --local-dir "$ARTIFACTS_DIR/hf_base/d18_20tpp_drope_50"
hf download crellis/d18-9tpp-hf-base             --local-dir "$ARTIFACTS_DIR/hf_base/d18_9tpp"
hf download crellis/d18-9tpp-drope-25-hf-base    --local-dir "$ARTIFACTS_DIR/hf_base/d18_9tpp_drope_25"
hf download crellis/d18-9tpp-drope-50-hf-base    --local-dir "$ARTIFACTS_DIR/hf_base/d18_9tpp_drope_50"
hf download crellis/d18-9tpp-drope-75-hf-base    --local-dir "$ARTIFACTS_DIR/hf_base/d18_9tpp_drope_75"
hf download crellis/d20-20tpp-hf-base            --local-dir "$ARTIFACTS_DIR/hf_base/d20_20tpp"
hf download crellis/d20-20tpp-drope-50-hf-base   --local-dir "$ARTIFACTS_DIR/hf_base/d20_20tpp_drope_50"
hf download crellis/d20-40tpp-hf-base            --local-dir "$ARTIFACTS_DIR/hf_base/d20_40tpp"
hf download crellis/d20-40tpp-drope-50-hf-base   --local-dir "$ARTIFACTS_DIR/hf_base/d20_40tpp_drope_50"
hf download crellis/d20-9tpp-hf-base             --local-dir "$ARTIFACTS_DIR/hf_base/d20_9tpp"
hf download crellis/d20-9tpp-drope-25-hf-base    --local-dir "$ARTIFACTS_DIR/hf_base/d20_9tpp_drope_25"
hf download crellis/d20-9tpp-drope-50-hf-base    --local-dir "$ARTIFACTS_DIR/hf_base/d20_9tpp_drope_50"
hf download crellis/d20-9tpp-drope-75-hf-base    --local-dir "$ARTIFACTS_DIR/hf_base/d20_9tpp_drope_75"

# ---------------- hf_sft ----------------
hf download crellis/d18-20tpp-hf-sft                  --local-dir "$ARTIFACTS_DIR/hf_sft/d18_20tpp"
hf download crellis/d18-20tpp-drope-50-hf-sft         --local-dir "$ARTIFACTS_DIR/hf_sft/d18_20tpp_drope_50"
hf download crellis/d18-20tpp-drope-50-long-hf-sft    --local-dir "$ARTIFACTS_DIR/hf_sft/d18_20tpp_drope_50_long"
hf download crellis/d18-20tpp-long-hf-sft             --local-dir "$ARTIFACTS_DIR/hf_sft/d18_20tpp_long"
hf download crellis/d18-9tpp-hf-sft                   --local-dir "$ARTIFACTS_DIR/hf_sft/d18_9tpp"
hf download crellis/d18-9tpp-drope-25-hf-sft          --local-dir "$ARTIFACTS_DIR/hf_sft/d18_9tpp_drope_25"
hf download crellis/d18-9tpp-drope-50-hf-sft          --local-dir "$ARTIFACTS_DIR/hf_sft/d18_9tpp_drope_50"
hf download crellis/d18-9tpp-drope-75-hf-sft          --local-dir "$ARTIFACTS_DIR/hf_sft/d18_9tpp_drope_75"
hf download crellis/d20-20tpp-hf-sft                  --local-dir "$ARTIFACTS_DIR/hf_sft/d20_20tpp"
hf download crellis/d20-20tpp-drope-50-hf-sft         --local-dir "$ARTIFACTS_DIR/hf_sft/d20_20tpp_drope_50"
hf download crellis/d20-20tpp-drope-50-long-hf-sft    --local-dir "$ARTIFACTS_DIR/hf_sft/d20_20tpp_drope_50_long"
hf download crellis/d20-20tpp-long-hf-sft             --local-dir "$ARTIFACTS_DIR/hf_sft/d20_20tpp_long"
hf download crellis/d20-40tpp-hf-sft                  --local-dir "$ARTIFACTS_DIR/hf_sft/d20_40tpp"
hf download crellis/d20-40tpp-drope-50-hf-sft         --local-dir "$ARTIFACTS_DIR/hf_sft/d20_40tpp_drope_50"
hf download crellis/d20-40tpp-drope-50-long-hf-sft    --local-dir "$ARTIFACTS_DIR/hf_sft/d20_40tpp_drope_50_long"
hf download crellis/d20-40tpp-long-hf-sft             --local-dir "$ARTIFACTS_DIR/hf_sft/d20_40tpp_long"
hf download crellis/d20-9tpp-hf-sft                   --local-dir "$ARTIFACTS_DIR/hf_sft/d20_9tpp"
hf download crellis/d20-9tpp-drope-25-hf-sft          --local-dir "$ARTIFACTS_DIR/hf_sft/d20_9tpp_drope_25"
hf download crellis/d20-9tpp-drope-50-hf-sft          --local-dir "$ARTIFACTS_DIR/hf_sft/d20_9tpp_drope_50"
hf download crellis/d20-9tpp-drope-75-hf-sft          --local-dir "$ARTIFACTS_DIR/hf_sft/d20_9tpp_drope_75"

# ---------------- base_checkpoints ----------------
hf download crellis/d18-20tpp-base_checkpoints            --local-dir "$ARTIFACTS_DIR/base_checkpoints/d18_20tpp"
hf download crellis/d18-20tpp-drope-50-base_checkpoints   --local-dir "$ARTIFACTS_DIR/base_checkpoints/d18_20tpp_drope_50"
hf download crellis/d18-9tpp-base_checkpoints             --local-dir "$ARTIFACTS_DIR/base_checkpoints/d18_9tpp"
hf download crellis/d18-9tpp-drope-25-base_checkpoints    --local-dir "$ARTIFACTS_DIR/base_checkpoints/d18_9tpp_drope_25"
hf download crellis/d18-9tpp-drope-50-base_checkpoints    --local-dir "$ARTIFACTS_DIR/base_checkpoints/d18_9tpp_drope_50"
hf download crellis/d18-9tpp-drope-75-base_checkpoints    --local-dir "$ARTIFACTS_DIR/base_checkpoints/d18_9tpp_drope_75"
hf download crellis/d20-20tpp-base_checkpoints            --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_20tpp"
hf download crellis/d20-20tpp-drope-50-base_checkpoints   --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_20tpp_drope_50"
hf download crellis/d20-40tpp-base_checkpoints            --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_40tpp"
hf download crellis/d20-40tpp-drope-50-base_checkpoints   --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_40tpp_drope_50"
hf download crellis/d20-9tpp-base_checkpoints             --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_9tpp"
hf download crellis/d20-9tpp-drope-25-base_checkpoints    --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_9tpp_drope_25"
hf download crellis/d20-9tpp-drope-50-base_checkpoints    --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_9tpp_drope_50"
hf download crellis/d20-9tpp-drope-75-base_checkpoints    --local-dir "$ARTIFACTS_DIR/base_checkpoints/d20_9tpp_drope_75"

# ---------------- chatsft_checkpoints ----------------
hf download crellis/d18-20tpp-chatsft_checkpoints                 --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_20tpp"
hf download crellis/d18-20tpp-drope-50-chatsft_checkpoints        --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_20tpp_drope_50"
hf download crellis/d18-20tpp-drope-50-long-chatsft_checkpoints   --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_20tpp_drope_50_long"
hf download crellis/d18-20tpp-long-chatsft_checkpoints            --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_20tpp_long"
hf download crellis/d18-9tpp-chatsft_checkpoints                  --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_9tpp"
hf download crellis/d18-9tpp-drope-25-chatsft_checkpoints         --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_9tpp_drope_25"
hf download crellis/d18-9tpp-drope-50-chatsft_checkpoints         --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_9tpp_drope_50"
hf download crellis/d18-9tpp-drope-75-chatsft_checkpoints         --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d18_9tpp_drope_75"
hf download crellis/d20-20tpp-chatsft_checkpoints                 --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_20tpp"
hf download crellis/d20-20tpp-drope-50-chatsft_checkpoints        --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_20tpp_drope_50"
hf download crellis/d20-20tpp-drope-50-long-chatsft_checkpoints   --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_20tpp_drope_50_long"
hf download crellis/d20-20tpp-long-chatsft_checkpoints            --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_20tpp_long"
hf download crellis/d20-40tpp-chatsft_checkpoints                 --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_40tpp"
hf download crellis/d20-40tpp-drope-50-chatsft_checkpoints        --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_40tpp_drope_50"
hf download crellis/d20-40tpp-drope-50-long-chatsft_checkpoints   --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_40tpp_drope_50_long"
hf download crellis/d20-40tpp-long-chatsft_checkpoints            --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_40tpp_long"
hf download crellis/d20-9tpp-chatsft_checkpoints                  --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_9tpp"
hf download crellis/d20-9tpp-drope-25-chatsft_checkpoints         --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_9tpp_drope_25"
hf download crellis/d20-9tpp-drope-50-chatsft_checkpoints         --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_9tpp_drope_50"
hf download crellis/d20-9tpp-drope-75-chatsft_checkpoints         --local-dir "$ARTIFACTS_DIR/chatsft_checkpoints/d20_9tpp_drope_75"
